import Footer from "./_layoutComponents/Footer";
import Navbar from "./_layoutComponents/Navbar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params: { lang } }: LayoutProps) {
  const handleChangeTheme = (e: MouseEvent) => {
    e.preventDefault();
  };

  return (
    <html lang="en">
      <body className="">
        <Navbar lang={lang} />
        {children}
        <Footer />
      </body>
    </html>
  );
}

type LayoutProps = {
  children: React.ReactNode;
  params: { lang: string };
};

